name: mobx_with_database
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+3
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.1+3

flutter:
  uses-material-design: true
